from th2agent.configs.settings import get_settings
import boto3
from io import BytesIO

settings = get_settings()



def _get_s3_client():
    return boto3.client(
        "s3",
        region_name=settings.s3_region,
        endpoint_url=settings.s3_endpoint,
        aws_access_key_id=settings.s3_access_key,
        aws_secret_access_key=settings.s3_access_key_secret,
)


def upload_file_to_s3(file_path: str, s3_key: str) -> str:
    s3=_get_s3_client()
    s3.upload_file(file_path, settings.s3_bucket_name, s3_key)
    return f"s3://{settings.s3_bucket_name}/{s3_key}"

def list_files_in_s3(prefix: str = ""):
    s3 = _get_s3_client()
    response = s3.list_objects_v2(
        Bucket=settings.s3_bucket_name,
        Prefix=prefix,
    )
    return [obj["Key"] for obj in response.get("Contents", [])]

def file_exists_in_s3(s3_key: str) -> bool:
    """Check if file exists in S3 by attempting to list it."""
    keys = list_files_in_s3(prefix=s3_key)
    return s3_key in keys


#the file is in memory or generated by the agent and we store it to s3
def upload_bytes_to_s3(content: bytes, s3_key: str, content_type: str = "application/octet-stream") -> str:
    s3 = _get_s3_client()
    file_obj = BytesIO(content)
    s3.upload_fileobj(
        file_obj,
        settings.s3_bucket_name,
        s3_key,
        ExtraArgs={"ContentType": content_type},
    )
    return s3_key

def download_file_from_s3(s3_key: str) -> bytes:
    """Download file content from S3 as bytes."""
    s3 = _get_s3_client()
    response = s3.get_object(Bucket=settings.s3_bucket_name, Key=s3_key)
    return response["Body"].read()



# Read file as text
def read_text_file_from_s3(s3_key: str, encoding: str = "utf-8") -> str:
    content = download_file_from_s3(s3_key)
    return content.decode(encoding)


# Delete file
def delete_file_from_s3(s3_key: str) -> bool:
    s3 = _get_s3_client()

    s3.delete_object(
        Bucket=settings.s3_bucket_name,
        Key=s3_key,
    )

    return True


