MODELS = [
    {
        "id": "anthropic/claude-sonnet-4-6",
        "name": "Claude Sonnet 4.6",
        "provider": "anthropic",
        "tag": "Latest",
    },
    {
        "id": "anthropic/claude-opus-4-6",
        "name": "Claude Opus 4.6",
        "provider": "anthropic",
        "tag": "Powerful",
    },
    {
        "id": "anthropic/claude-haiku-4-5-20251001",
        "name": "Claude Haiku 4.5",
        "provider": "anthropic",
        "tag": "Fast",
    },
    {
        "id": "anthropic/claude-sonnet-4-5-20250929",
        "name": "Claude Sonnet 4.5",
        "provider": "anthropic",
        "tag": "Default",
    },
    {
        "id": "anthropic/claude-opus-4-0-20250514",
        "name": "Claude Opus 4",
        "provider": "anthropic",
        "tag": None,
    },
    {
        "id": "mistral/mistral-large-latest",
        "name": "Mistral Large 3",
        "provider": "mistral",
        "tag": "Recommended",
    },
    {
        "id": "mistral/devstral-small-latest",
        "name": "Devstral Small 2",
        "provider": "mistral",
        "tag": "Code",
    },
    {
        "id": "mistral/mistral-small-latest",
        "name": "Mistral Small 3",
        "provider": "mistral",
        "tag": "Fast",
    },
    {
        "id": "mistral/codestral-latest",
        "name": "Codestral",
        "provider": "mistral",
        "tag": "Code",
    },
    {
        "id": "mistral/open-mistral-nemo",
        "name": "Mistral Nemo",
        "provider": "mistral",
        "tag": "Open",
    },
    {
        "id": "openai/o3",
        "name": "o3",
        "provider": "openai",
        "tag": "Reasoning",
    },
    {
        "id": "openai/o4-mini",
        "name": "o4-mini",
        "provider": "openai",
        "tag": "Fast reasoning",
    },
    {
        "id": "openai/o3-pro",
        "name": "o3 Pro",
        "provider": "openai",
        "tag": "Deep reasoning",
    },
    {
        "id": "openai/gpt-4.1",
        "name": "GPT-4.1",
        "provider": "openai",
        "tag": "Coding",
    },
    {
        "id": "openai/gpt-4.1-mini",
        "name": "GPT-4.1 Mini",
        "provider": "openai",
        "tag": "Fast",
    },
    {
        "id": "openai/gpt-4.1-nano",
        "name": "GPT-4.1 Nano",
        "provider": "openai",
        "tag": "Fastest",
    },
    {
        "id": "gemini/gemini-3.1-pro-preview",
        "name": "Gemini 3.1 Pro",
        "provider": "gemini",
        "tag": "Latest",
    },
    # gemini-3-pro, gemini-2.0-flash and gemini-2.0-pro were removed on
    # 2026-09-25: Google answered 404 (or the run failed) for each on
    # agent-dev, and gemini-2.0-flash's 404 names gemini-3.8-flash instead.
    {
        "id": "gemini/gemini-3.8-flash",
        "name": "Gemini 3.8 Flash",
        "provider": "gemini",
        "tag": "Fast",
    },
    {
        "id": "deepseek/deepseek-chat",
        "name": "DeepSeek V3.2",
        "provider": "deepseek",
        "tag": "Recommended",
    },
    {
        "id": "deepseek/deepseek-reasoner",
        "name": "DeepSeek V3.2 R1",
        "provider": "deepseek",
        "tag": "Reasoning",
    },
    {
        "id": "groq/meta-llama/llama-4-maverick-17b-128e-instruct",
        "name": "Llama 4 Maverick",
        "provider": "groq",
        "tag": "Powerful",
    },
    {
        "id": "groq/meta-llama/llama-4-scout-17b-16e-instruct",
        "name": "Llama 4 Scout",
        "provider": "groq",
        "tag": "Fast",
    },
    {
        "id": "groq/openai/gpt-oss-120b",
        "name": "GPT-OSS 120B",
        "provider": "groq",
        "tag": "Open",
    },
    {
        "id": "groq/qwen/qwen-3-32b",
        "name": "Qwen 3 32B",
        "provider": "groq",
        "tag": "Preview",
    },
    {
        "id": "groq/llama-3.3-70b-versatile",
        "name": "Llama 3.3 70B",
        "provider": "groq",
        "tag": None,
    },
]
