from apowerb.configs.settings import get_settings
import boto3
from botocore.exceptions import ClientError
from io import BytesIO

settings = get_settings()



def _get_s3_client():
    return boto3.client(
        "s3",
        region_name=settings.s3_region,
        endpoint_url=settings.s3_endpoint,
        aws_access_key_id=settings.s3_access_key,
        aws_secret_access_key=settings.s3_access_key_secret,
)


def upload_file_to_s3(file_path: str, s3_key: str) -> str:
    s3=_get_s3_client()
    s3.upload_file(file_path, settings.s3_bucket_name, s3_key)
    return f"s3://{settings.s3_bucket_name}/{s3_key}"

def list_files_in_s3(prefix: str = ""):
    s3 = _get_s3_client()
    response = s3.list_objects_v2(
        Bucket=settings.s3_bucket_name,
        Prefix=prefix,
    )
    return [obj["Key"] for obj in response.get("Contents", [])]

def file_exists_in_s3(s3_key: str) -> bool:
    """Check if file exists in S3 by attempting to list it."""
    keys = list_files_in_s3(prefix=s3_key)
    return s3_key in keys


#the file is in memory or generated by the agent and we store it to s3
def upload_bytes_to_s3(
    content: bytes,
    s3_key: str,
    content_type: str = "application/octet-stream",
    metadata: dict[str, str] | None = None,
) -> str:
    s3 = _get_s3_client()
    file_obj = BytesIO(content)
    extra_args = {"ContentType": content_type}
    if metadata:
        extra_args["Metadata"] = metadata
    s3.upload_fileobj(
        file_obj,
        settings.s3_bucket_name,
        s3_key,
        ExtraArgs=extra_args,
    )
    return s3_key


def get_object_with_metadata(s3_key: str) -> dict:
    """Fetch an object's body along with its content type, custom metadata
    and last-modified timestamp, in a single request.

    Raises ``botocore.exceptions.ClientError`` when the key does not exist —
    callers decide whether to translate that into "not found" or propagate.
    """
    s3 = _get_s3_client()
    response = s3.get_object(Bucket=settings.s3_bucket_name, Key=s3_key)
    return {
        "body": response["Body"].read(),
        "content_type": response.get("ContentType"),
        "metadata": response.get("Metadata", {}),
        "last_modified": response.get("LastModified"),
    }


def head_object_in_s3(s3_key: str) -> dict | None:
    """Return content type / custom metadata / last-modified for an object
    without downloading its body. Returns None if the object does not exist.
    """
    s3 = _get_s3_client()
    try:
        response = s3.head_object(Bucket=settings.s3_bucket_name, Key=s3_key)
    except ClientError as exc:
        error_code = exc.response.get("Error", {}).get("Code")
        if error_code in ("404", "NoSuchKey", "NotFound"):
            return None
        raise
    return {
        "content_type": response.get("ContentType"),
        "metadata": response.get("Metadata", {}),
        "last_modified": response.get("LastModified"),
    }


def download_file_from_s3(s3_key: str) -> bytes:
    """Download file content from S3 as bytes."""
    return get_object_with_metadata(s3_key)["body"]



# Read file as text
def read_text_file_from_s3(s3_key: str, encoding: str = "utf-8") -> str:
    content = download_file_from_s3(s3_key)
    return content.decode(encoding)


# Delete file
def delete_file_from_s3(s3_key: str) -> bool:
    s3 = _get_s3_client()

    s3.delete_object(
        Bucket=settings.s3_bucket_name,
        Key=s3_key,
    )

    return True


